print("Hi, Whats Your name?")
name = input()
print("Hi " + name)
print("give me a number please!")
number1 = input()
print("another number please!")
number2 = input()
print("Your first number is: " + number1)
print("Your second number is: " + number2)
sum = int(number1) + int(number2)
print("sum of your numbers is: " + str(sum))
print("thank you")
